site_name: SCUBAS Documentation
repo_url: https://github.com/shibaji7/SCUBAS
theme: 
  name: "material"
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.path

plugins:
    - search
    - glightbox
    - awesome-pages
    - mkdocstrings:
        enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
        default_handler: python
        handlers:
          python:
            paths: [".."]  
            options:
              show_root_heading: true
              show_source: true
              members_order: source
     
markdown_extensions:
    - extra
    - admonition
    - toc
    - tables
    - attr_list
    - toc:
        permalink: true
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.betterem
    - pymdownx.caret
    - pymdownx.mark
    - pymdownx.tilde
    - attr_list
    - md_in_html
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.highlight
    - pymdownx.details
    - footnotes
        
extra_javascript:
    - javascripts/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
    - Home: index.md
    - Installation: user/install.md  
    - INTERMAGNET Data Access: user/intermagnet.md 
    - Citing: user/citing.md
    - Tutorials: 
            - TLM Theory: tutorial/theory.md
            - Long and Short Cables: tutorial/elsc.md
            - Active Termination: tutorial/active.md
            - Network Modeling: tutorial/netmodel.md
            - Case Studies/Codes: tutorial/conduct.md
            - Event Study (1989 Strom): tutorial/1989.md
            - Extreme Value Analysis: tutorial/eva.md
            - Uncertainity Quantification: tutorial/uq.md
    - Code Documentation:
            - Cables: dev/cables.md
            - Ocean/Earth Conductivity: dev/conductivity.md
            - Datasets: dev/datasets.md
            - Ocean/Earth Model: dev/models.md
            - Plotting Library: dev/plotlib.md
            - Utility Module: dev/utils.md